pub(crate) mod agent_resolver;
pub(crate) mod control;
mod registry;
pub(crate) mod response_observation;
pub(crate) mod role;
pub(crate) mod status;
pub(crate) mod turn_queue;
mod user_control;

pub(crate) use codex_protocol::protocol::AgentStatus;
pub(crate) use control::AgentControl;
pub(crate) use registry::AgentMetadata;
pub(crate) use registry::exceeds_thread_spawn_depth_limit;
pub(crate) use registry::next_thread_spawn_depth;
pub(crate) use status::agent_status_from_event;
pub use user_control::UserAgentFinalResponseHandling;
pub use user_control::UserAgentForkMode;
pub use user_control::UserAgentObservationBinding;
pub use user_control::UserAgentObservationMode;
pub use user_control::UserAgentOwnershipTransfer;
pub use user_control::UserAgentPromptResult;
pub use user_control::UserAgentQueuedTurn;
pub use user_control::UserAgentReservedPromptResult;
pub use user_control::UserAgentResponseHandling;
pub use user_control::UserAgentResumeResult;
pub use user_control::UserAgentSpawnOptions;
pub use user_control::UserAgentSpawnResult;
