// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentForkMode } from "./AgentForkMode";
import type { AgentObservationMode } from "./AgentObservationMode";
import type { AgentResponseHandling } from "./AgentResponseHandling";
import type { UserInput } from "./UserInput";

/**
 * A user-authored multi-agent control operation.
 */
export type AgentControlAction = { "type": "spawn",
/**
 * Omitted selects the default child configuration.
 */
role: string | null,
/**
 * Omitted creates a real idle child without starting its first turn.
 */
input: Array<UserInput> | null, forkMode: AgentForkMode,
/**
 * Omitted uses passive final-response delivery.
 */
responseHandling: AgentResponseHandling | null, } | { "type": "prompt",
/**
 * Root-scoped ref or nickname, or a canonical thread UUID.
 */
target: string, input: Array<UserInput>,
/**
 * Omitted uses passive final-response delivery.
 */
responseHandling: AgentResponseHandling | null, } | { "type": "reservedPrompt",
/**
 * Canonical target thread UUID.
 */
target: string, input: Array<UserInput>, } | { "type": "queuedPrompt",
/**
 * Root-scoped ref or nickname, or a canonical thread UUID.
 */
target: string, input: Array<UserInput>,
/**
 * Omitted uses passive final-response delivery.
 */
responseHandling: AgentResponseHandling | null, } | { "type": "resume",
/**
 * Root-scoped ref or nickname, or a canonical thread UUID for explicit adoption.
 */
target: string,
/**
 * Omitted reserves passive delivery for the next admitted target turn.
 */
responseHandling: AgentResponseHandling | null, } | { "type": "interrupt", target: string, input: Array<UserInput> | null,
/**
 * Valid only when `input` is present.
 */
responseHandling: AgentResponseHandling | null, } | { "type": "close", target: string,
/**
 * Omitted replays a completed response passively when it is absent from model context.
 */
responseHandling: AgentResponseHandling | null, } | { "type": "observe", target: string, responseHandling: AgentObservationMode, };
