// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a user input submission is known to have been admitted.
 */
export type AgentInputOutcome = "admitted" | "queued" | "unknown";
