// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentFinalResponseHandling } from "./AgentFinalResponseHandling";
import type { AgentObservationBinding } from "./AgentObservationBinding";

/**
 * Committed outcome of a user-authored multi-agent control operation.
 */
export type AgentControlOutcome = { "type": "spawned", targetThreadId: string, ref: string | null, nickname: string | null,
/**
 * Non-retryable degradation after child input admission.
 */
postAdmissionWarning: string | null, } | { "type": "prompted", targetThreadId: string, submissionId: string,
/**
 * Queue admission was selected; an idle target may already be starting this input.
 */
queued: boolean,
/**
 * Non-retryable degradation after target input admission.
 */
postAdmissionWarning: string | null, } | { "type": "reservedPrompted", targetThreadId: string, submissionId: string, turnId: string,
/**
 * Non-retryable degradation after target input admission.
 */
postAdmissionWarning: string | null, } | { "type": "resumed", targetThreadId: string, ref: string | null, nickname: string | null, observationBinding: AgentObservationBinding | null,
/**
 * Degradation that occurred after an exclusive ownership transfer committed.
 */
postCommitWarning: string | null, } | { "type": "interrupted", targetThreadId: string, submissionId: string | null,
/**
 * Non-retryable degradation after follow-up input admission.
 */
postAdmissionWarning: string | null, } | { "type": "closed", targetThreadId: string, } | { "type": "observed", targetThreadId: string, previousResponseHandling: AgentFinalResponseHandling, responseHandling: AgentFinalResponseHandling, binding: AgentObservationBinding, };
