// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-authored state for a target's attributed reply route.
 */
export type AgentReplyRouteMode = "enabled" | "disabled";
