// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Committed adoption label mapping. Thread identity remains unchanged.
 */
export type AgentTaskPathMapping = { threadId: string, previousTaskPath: string | null, taskPath: string | null, };
