// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable lifecycle state of an alias in one root namespace.
 */
export type AgentAliasState = "active" | "closed" | "transferred";
