// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentFinalResponseHandling } from "./AgentFinalResponseHandling";
import type { AgentInputOutcome } from "./AgentInputOutcome";
import type { AgentObservationBinding } from "./AgentObservationBinding";
import type { AgentReplyRouteMode } from "./AgentReplyRouteMode";
import type { AgentTaskPathMapping } from "./AgentTaskPathMapping";

/**
 * Outcome of a user-authored operation; input may be admitted or indeterminate after enqueue.
 */
export type AgentControlOutcome = { "type": "spawned", targetThreadId: string, ref: string | null, nickname: string | null, inputOutcome: AgentInputOutcome | null, taskPath: string | null,
/**
 * Non-retryable degradation after child input admission or uncertain routing.
 */
postAdmissionWarning: string | null, } | { "type": "prompted", targetThreadId: string, submissionId: string, inputOutcome: AgentInputOutcome,
/**
 * Non-retryable degradation after target input admission or uncertain routing.
 */
postAdmissionWarning: string | null, } | { "type": "reservedPrompted", targetThreadId: string, submissionId: string, inputOutcome: AgentInputOutcome,
/**
 * The admitted target turn when routing can prove it; null means the input outcome
 * is indeterminate after enqueue and must not be retried automatically.
 */
turnId: string | null,
/**
 * Non-retryable degradation after target input admission, including an indeterminate
 * target turn after enqueue.
 */
postAdmissionWarning: string | null, } | { "type": "resumed", targetThreadId: string, ref: string | null, nickname: string | null, taskPath: string | null, taskPathMapping: Array<AgentTaskPathMapping>, observationBinding: AgentObservationBinding | null,
/**
 * Degradation that occurred after an exclusive ownership transfer committed.
 */
postCommitWarning: string | null, } | { "type": "interrupted", targetThreadId: string, submissionId: string | null, inputOutcome: AgentInputOutcome | null,
/**
 * Non-retryable degradation after follow-up input admission or uncertain routing.
 */
postAdmissionWarning: string | null, } | { "type": "closed", targetThreadId: string, } | { "type": "observed", targetThreadId: string, observerThreadId: string, previousResponseHandling: AgentFinalResponseHandling, responseHandling: AgentFinalResponseHandling, binding: AgentObservationBinding, } | { "type": "replyRouteChanged", targetThreadId: string, recipientThreadId: string, previousMode: AgentReplyRouteMode | null, mode: AgentReplyRouteMode, } | { "type": "subtreeMessagingChanged", rootThreadId: string, previousMode: AgentReplyRouteMode | null, mode: AgentReplyRouteMode, };
