// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResponseHandling } from "./AgentResponseHandling";

/**
 * Queue provenance and response handling bound to a newly started target turn.
 */
export type AgentQueueTurnMetadata = { queueId: string, sourceThreadId: string,
/**
 * Committed queue-entry policy, including queued source delivery; `null` when source-side
 * persistence degraded after admission.
 */
responseHandling: AgentResponseHandling | null, };
