// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * Trusted send-time identity, retained even when current aliases or ownership change.
 */
export type AgentInputIdentity = { threadId: string, nickname: string | null, agentRef: string | null, taskPath: string | null, role: string | null, model: string | null, reasoningEffort: ReasoningEffort | null, };
