// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact target work whose final-response handling was replaced.
 */
export type AgentObservationBinding = "activeTurn" | "nextTurn" | "undeliveredCompletion";
