// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAliasState } from "./AgentAliasState";

/**
 * Root-scoped user-facing aliases for one canonical agent thread.
 */
export type AgentAlias = { threadId: string, ref: string, nickname: string | null, state: AgentAliasState, };
