// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentInputIdentity } from "./AgentInputIdentity";

/**
 * Presentation-only provenance; the original message and attachments are in the item's input.
 */
export type AgentInputAttribution = { sender: AgentInputIdentity, recipient: AgentInputIdentity, senderTurnId: string, };
