// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authoritative final-response policy accepted by `agent/control` observe.
 */
export type AgentObservationMode = "passive" | "wake" | "presentation";
