// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResponseHandling } from "./AgentResponseHandling";
import type { UserInput } from "./UserInput";

/**
 * Structured input waiting to start a distinct target turn.
 */
export type AgentQueueEntry = { id: string, sourceThreadId: string, targetThreadId: string, input: Array<UserInput>, promptPreview: string, responseHandling: AgentResponseHandling, authoredSelector: string | null, };
