// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final-response handling selected by an explicit user observation replacement.
 */
export type AgentFinalResponseHandling = "none" | "passive" | "wake" | "presentation";
