// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadId } from "../ThreadId";
import type { CollabAgentInputResult } from "./CollabAgentInputResult";

export type CollabAgentInputBatch = {
/**
 * Shared, normalized handling flags. Empty means default passive handling.
 */
flags: string,
/**
 * Sender identity for a child-originated live/replayed batch presentation.
 */
senderThreadId: ThreadId | null,
/**
 * Empty while the batch is in progress; populated only on normal completion.
 */
results: Array<CollabAgentInputResult>, };
