// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentInputStatus } from "./CollabAgentInputStatus";

export type CollabAgentInputResult = {
/**
 * Canonical ref when available, otherwise UUID or the unresolved authored selector.
 */
target: string,
/**
 * Joins the parent item's receiver metadata; absent for unresolved selectors.
 */
receiverThreadId: string | null, status: CollabAgentInputStatus, error: string | null, hint: string | null, };
