// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentInputResult } from "./CollabAgentInputResult";

export type CollabAgentInputBatch = {
/**
 * Shared, normalized handling flags. Empty means default passive handling.
 */
flags: string,
/**
 * Empty while the batch is in progress; populated only on normal completion.
 */
results: Array<CollabAgentInputResult>, };
