// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollabAgentRef = {
/**
 * Thread ID of the receiving agent.
 */
threadId: string,
/**
 * Trusted root-scoped numeric reference, when available from the agent alias.
 */
agentRef: string | null,
/**
 * Trusted task assignment path, when available from the agent alias.
 */
taskPath: string | null,
/**
 * Optional nickname assigned to the receiving agent.
 */
agentNickname: string | null,
/**
 * Optional role assigned to the receiving agent.
 */
agentRole: string | null, };
