// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Presentation provenance for incoming communication, not sender authority or a delivery receipt.
 */
export type InterAgentMessageSource = { author: string, recipient: string, };
