// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadItem } from "./ThreadItem";

export type ItemStartedNotification = { item: ThreadItem, threadId: string, turnId: string,
/**
 * Unix timestamp (in milliseconds) when this item lifecycle started.
 */
startedAtMs: number,
/**
 * Advisory Unix-millisecond estimate for the current wait, or null when unavailable.
 * This is not a process deadline and must not be restored as live state during replay.
 */
deadlineAtMs: number | null, };
