// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxReadSelector } from "./MailboxReadSelector";

/**
 * A committed `check_mail` outcome; message bodies are never included.
 */
export type MailboxReadItem = {
/**
 * The originating tool call ID, scoped by the containing turn.
 */
id: string, selector: MailboxReadSelector,
/**
 * Number of messages terminally acknowledged as consumed.
 */
consumedCount: number,
/**
 * Number of selected messages terminally rejected before consumption.
 */
rejectedCount: number, };
