// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxReadSelector } from "./MailboxReadSelector";

export type MailboxReadItem = { id: string, selector: MailboxReadSelector, consumedCount: number, rejectedCount: number, };
