// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Startup credential selection, without credentials or absolute auth paths.
 *
 * The opaque ID describes host-local configuration, not an authenticated
 * account, and cannot be used to compare credential paths across hosts.
 */
export type ServerAuthProfile = { profileOpaqueId: string, displayLabel: string, };
