// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Duration policy for a `write_stdin` wait.
 */
export type TerminalWaitMode = "timed" | "untilExit";
