// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reason a `write_stdin` wait stopped waiting.
 */
export type TerminalWaitCompletionReason = "exited" | "timeout" | "input" | "cancelled" | "failed";
