// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalWait } from "./TerminalWait";

export type TerminalInteractionNotification = { threadId: string, turnId: string, itemId: string, processId: string, stdin: string,
/**
 * Unix timestamp (in milliseconds) when a bounded wait should report back.
 * Until-exit waits and completed waits have no deadline.
 */
deadlineAtMs: number | null,
/**
 * Lifecycle metadata for a `write_stdin` wait. Null for legacy events.
 */
wait: TerminalWait | null, };
