// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalWaitCompletionReason } from "./TerminalWaitCompletionReason";
import type { TerminalWaitMode } from "./TerminalWaitMode";

/**
 * Start or completion metadata for one `write_stdin` wait.
 */
export type TerminalWait = { "phase": "started",
/**
 * The `write_stdin` function-call ID, distinct from the command item ID.
 */
interactionId: string,
/**
 * Unix timestamp in milliseconds when the wait began.
 */
startedAtMs: number,
/**
 * Whether this wait has a deadline or continues until process exit.
 */
mode: TerminalWaitMode, } | { "phase": "finished",
/**
 * The `write_stdin` function-call ID matching the start event.
 */
interactionId: string,
/**
 * Actual elapsed wait time in milliseconds.
 */
elapsedMs: number,
/**
 * Why the wait finished.
 */
reason: TerminalWaitCompletionReason, };
