// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalWait } from "./TerminalWait";

export type TerminalInteractionNotification = { threadId: string, turnId: string, itemId: string, processId: string, stdin: string,
/**
 * Advisory Unix-millisecond empty-poll estimate, or null when cleared or unavailable.
 */
deadlineAtMs: number | null, wait: TerminalWait | null, };
