// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pending counts grouped by the canonical mailbox sender identity.
 */
export type ThreadMailboxPendingSender = { "type": "user", count: number, } | { "type": "agent", threadId: string, count: number, };
