// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResponseFinalDelivery } from "../AgentResponseFinalDelivery";
import type { FunctionCallOutputBody } from "../FunctionCallOutputBody";
import type { ImageGenerationItem } from "../ImageGenerationItem";
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { MessagePhase } from "../MessagePhase";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { SleepItem } from "../SleepItem";
import type { UserAgentControlAction } from "../UserAgentControlAction";
import type { UserAgentControlStatus } from "../UserAgentControlStatus";
import type { UserAgentForkMode } from "../UserAgentForkMode";
import type { WebSearchItem } from "../WebSearchItem";
import type { JsonValue } from "../serde_json/JsonValue";
import type { AgentInputAttribution } from "./AgentInputAttribution";
import type { AgentInputOutcome } from "./AgentInputOutcome";
import type { AgentMessageDelivery } from "./AgentMessageDelivery";
import type { AgentTaskPathMapping } from "./AgentTaskPathMapping";
import type { AsyncUserInputQuestion } from "./AsyncUserInputQuestion";
import type { CollabAgentInputBatch } from "./CollabAgentInputBatch";
import type { CollabAgentRef } from "./CollabAgentRef";
import type { CollabAgentState } from "./CollabAgentState";
import type { CollabAgentTool } from "./CollabAgentTool";
import type { CollabAgentToolCallStatus } from "./CollabAgentToolCallStatus";
import type { CommandAction } from "./CommandAction";
import type { CommandExecutionSource } from "./CommandExecutionSource";
import type { CommandExecutionStatus } from "./CommandExecutionStatus";
import type { DynamicToolCallOutputContentItem } from "./DynamicToolCallOutputContentItem";
import type { DynamicToolCallStatus } from "./DynamicToolCallStatus";
import type { FileUpdateChange } from "./FileUpdateChange";
import type { HookPromptFragment } from "./HookPromptFragment";
import type { InterAgentMessageSource } from "./InterAgentMessageSource";
import type { MailboxReadItem } from "./MailboxReadItem";
import type { McpAppUi } from "./McpAppUi";
import type { McpToolCallAppContext } from "./McpToolCallAppContext";
import type { McpToolCallError } from "./McpToolCallError";
import type { McpToolCallResult } from "./McpToolCallResult";
import type { McpToolCallStatus } from "./McpToolCallStatus";
import type { MemoryCitation } from "./MemoryCitation";
import type { PatchApplyStatus } from "./PatchApplyStatus";
import type { SubAgentActivityKind } from "./SubAgentActivityKind";
import type { ThreadShellCommandResponseHandling } from "./ThreadShellCommandResponseHandling";
import type { UserInput } from "./UserInput";

export type ThreadItem = { "type": "userMessage", id: string, clientId: string | null, content: Array<UserInput>, } | { "type": "hookPrompt", id: string, fragments: Array<HookPromptFragment>, } | { "type": "agentMessage", id: string, text: string, interAgentSource: InterAgentMessageSource | null, attribution: AgentInputAttribution | null, input: Array<UserInput> | null, phase: MessagePhase | null, memoryCitation: MemoryCitation | null, delivery: AgentMessageDelivery | null, questions: Array<AsyncUserInputQuestion> | null, } | { "type": "functionCallOutput", id: string, name: string, namespace: string | null, output: FunctionCallOutputBody, } | { "type": "plan", id: string, text: string, } | { "type": "reasoning", id: string, summary: Array<string>, content: Array<string>, } | { "type": "commandExecution", id: string,
/**
 * Trusted first-party plugin id when this command resolves to one plugin script.
 */
pluginId: string | null,
/**
 * Safe plugin-relative path when this command resolves to one plugin script.
 */
scriptPath: string | null,
/**
 * The command to be executed.
 */
command: string,
/**
 * The command's working directory.
 */
cwd: LegacyAppPathString,
/**
 * Identifier for the underlying PTY process (when available).
 */
processId: string | null, source: CommandExecutionSource,
/**
 * Completion delivery policy for a user-authored shell command.
 * `None` for model-authored and unified-exec commands.
 */
userShellResponseHandling: ThreadShellCommandResponseHandling | null, status: CommandExecutionStatus,
/**
 * A best-effort parsing of the command to understand the action(s) it will perform.
 * This returns a list of CommandAction objects because a single shell command may
 * be composed of many commands piped together.
 */
commandActions: Array<CommandAction>,
/**
 * The command's output, aggregated from stdout and stderr.
 */
aggregatedOutput: string | null,
/**
 * The command's exit code.
 */
exitCode: number | null,
/**
 * The duration of the command execution in milliseconds.
 */
durationMs: number | null, } | { "type": "fileChange", id: string, changes: Array<FileUpdateChange>, status: PatchApplyStatus, } | { "type": "mcpToolCall", id: string, server: string, tool: string, status: McpToolCallStatus, arguments: JsonValue, appContext: McpToolCallAppContext | null,
/**
 * Legacy compatibility field; prefer `mcpAppUi.resourceUri` when available.
 */
mcpAppResourceUri?: string,
/**
 * Presentation captured from the invoked descriptor; absent in older history.
 */
mcpAppUi: McpAppUi | null, pluginId: string | null, readOnlyHint: boolean | null, result: McpToolCallResult | null, error: McpToolCallError | null,
/**
 * The duration of the MCP tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "dynamicToolCall", id: string, namespace: string | null, tool: string, arguments: JsonValue, status: DynamicToolCallStatus, contentItems: Array<DynamicToolCallOutputContentItem> | null, success: boolean | null,
/**
 * The duration of the dynamic tool call in milliseconds.
 */
durationMs: number | null, } | { "type": "mailboxRead" } & MailboxReadItem | { "type": "collabAgentToolCall",
/**
 * Per-recipient admission outcomes for array-target sends; errors may follow admission.
 */
inputBatch: CollabAgentInputBatch | null,
/**
 * Unique identifier for this collab tool call.
 */
id: string,
/**
 * Name of the collab tool that was invoked.
 */
tool: CollabAgentTool,
/**
 * Current status of the collab tool call.
 */
status: CollabAgentToolCallStatus,
/**
 * Whether commentary from the receiver is requested.
 */
observeCommentary?: boolean,
/**
 * Whether the receiver's terminal response should wake the sender.
 */
wakeOnCompletion?: boolean,
/**
 * Whether this V1 lifecycle call granted the target an exact-turn reply route.
 */
targetMessages?: boolean,
/**
 * Whether this V1 send was queued as a distinct future target turn.
 */
queueInput?: boolean,
/**
 * Whether this V1 send explicitly requested mailbox delivery (`send_input` with `w:z`).
 * This is presentation metadata, not evidence of receiver execution or visibility.
 */
mailboxInput: boolean | null,
/**
 * Thread ID of the agent issuing the collab request.
 */
senderThreadId: string,
/**
 * Thread ID of the receiving agent, when applicable. In case of spawn operation,
 * this corresponds to the newly spawned agent.
 */
receiverThreadIds: Array<string>,
/**
 * Receiver metadata, when available. Absent in older history and
 * populated for new collab tool calls.
 */
receiverAgents: Array<CollabAgentRef>,
/**
 * Prompt text sent as part of the collab tool call, when available.
 */
prompt: string | null,
/**
 * Model requested for the spawned agent, when applicable.
 */
model: string | null,
/**
 * Reasoning effort requested for the spawned agent, when applicable.
 */
reasoningEffort: ReasoningEffort | null,
/**
 * Last known status of the target agents, when available.
 */
agentsStates: { [key in string]?: CollabAgentState }, } | { "type": "subAgentActivity", id: string, kind: SubAgentActivityKind, agentThreadId: string, agentPath: string, prompt: string | null, } | { "type": "userAgentControl", id: string, action: UserAgentControlAction, authoredSelector: string | null, targetThreadId: string | null, observerThreadId: string | null, authoredObserverSelector: string | null, replyRecipientThreadId: string | null, previousOwnerSessionId: string | null, newOwnerSessionId: string | null, ref: string | null, nickname: string | null, role: string | null, task: string | null, taskPath: string | null, taskPathMapping: Array<AgentTaskPathMapping>, model: string | null, reasoningEffort: ReasoningEffort | null, promptPreview: string | null, resumedTarget: boolean, forkMode: UserAgentForkMode | null, observeCommentary: boolean | null, finalResponse: AgentResponseFinalDelivery | null, targetMessages: boolean | null, queueInput: boolean | null, inputOutcome: AgentInputOutcome | null, status: UserAgentControlStatus, error: string | null, } | { "type": "webSearch" } & WebSearchItem | { "type": "imageView", id: string, path: LegacyAppPathString, } | { "type": "sleep" } & SleepItem | { "type": "imageGeneration" } & ImageGenerationItem | { "type": "enteredReviewMode", id: string, review: string, } | { "type": "exitedReviewMode", id: string, review: string, } | { "type": "contextCompaction", id: string, summary: string | null, message: string | null, decodeError: string | null,
/**
 * Skill names in the model-visible inventory installed after this compaction.
 */
availableSkills: Array<string>, };
