// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Acknowledges durable shutdown and removal of the captured runtime instances.
 */
export type ThreadUnloadResponse = { rootThreadId: string, unloadedThreadIds: Array<string>, };
