// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadShellCommandResponseHandling } from "./ThreadShellCommandResponseHandling";

export type ThreadShellCommandParams = { threadId: string,
/**
 * Shell command string evaluated by the thread's configured shell.
 * Unlike `command/exec`, this intentionally preserves shell syntax
 * such as pipes, redirects, and quoting. This runs unsandboxed with full
 * access rather than inheriting the thread sandbox policy.
 */
command: string,
/**
 * Maximum execution time in milliseconds. Omission or null uses the configured
 * user-shell default, which is unlimited unless overridden. Must be non-negative;
 * an explicit zero requests an immediate timeout. Does not affect the immediate
 * RPC acknowledgement.
 */
timeoutMs?: number | null,
/**
 * Optional completion delivery policy. Omission preserves passive model delivery.
 */
responseHandling?: ThreadShellCommandResponseHandling | null, };
