// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stop and unload the owning root and its loaded spawn descendants.
 */
export type ThreadUnloadParams = {
/**
 * Any thread in the owning spawn subtree, including the root.
 */
threadId: string, };
