// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadShellCommandFinalDelivery } from "./ThreadShellCommandFinalDelivery";

export type ThreadShellCommandResponseHandling = {
/**
 * Whether the completed result is delivered passively, wakes the thread, or stays
 * presentation-only.
 */
finalDelivery: ThreadShellCommandFinalDelivery,
/**
 * Whether execution waits for every earlier user-shell submission in this thread.
 */
queueCommand: boolean, };
