// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentQueueTurnMetadata } from "./AgentQueueTurnMetadata";
import type { Turn } from "./Turn";

export type TurnStartedNotification = { threadId: string, turn: Turn,
/**
 * Present when this exact turn was admitted from the shared agent queue.
 */
agentQueue: AgentQueueTurnMetadata | null, };
