// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final-response handling retained as durable evidence for an observer.
 */
export type AgentResponseFinalDelivery = "none" | "presentation_only" | "passive" | "wake";
