// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal outcome of an interruptible `clock.sleep` tool call.
 */
export type SleepOutcome = "completed" | "interrupted" | "error";
