// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAgentControlAction = "spawn" | "prompt" | "queued_prompt" | "resume" | "interrupt" | "close" | "observe" | "reply_route" | "subtree_messaging";
